version: '3.9'
services:

  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "/myapp/bin/migrate up && /myapp/bin/api" ]
    restart: always

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=notification-hub
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d notification-hub" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always
